POST http://localhost:50403/v1/recipes

{
  "en": {
    "message": "New recipe out now",
    "url": "https://nononsense.cooking/r/1"
  },
  "de": {
    "message": "Neues Rezept!\nSchau es dir auf https://nononsense.cooking/de-DE/r/KUvCHXi5t8/spinatwraps-mit-dillcreme an!",
    "url": "https://nononsense.cooking/r/1"
  }
}
