#!/usr/bin/env bash
# Fetch popular recipe slugs from Plausible breakdown API, write data/popular.yaml, rebuild site.
# Requires: curl, jq, hugo on PATH
set -euo pipefail

: "${PLAUSIBLE_API_KEY:?Set PLAUSIBLE_API_KEY}"
: "${PLAUSIBLE_BASE_URL:=https://plausible.riesinger.dev}"
: "${SITE_ID:=nononsense.cooking}"
: "${PERIOD:=6mo}"
: "${LIMIT:=30}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

curl -sSf "${PLAUSIBLE_BASE_URL}/api/v1/stats/breakdown" \
  -H "Authorization: Bearer ${PLAUSIBLE_API_KEY}" \
  -G \
  --data-urlencode "site_id=${SITE_ID}" \
  --data-urlencode "period=${PERIOD}" \
  --data-urlencode "property=event:page" \
  --data-urlencode "limit=${LIMIT}" \
  >"$TMP/body.json"

last_slug() {
  sed 's#/*$##' | awk -F/ '{print $NF}'
}

write_filtered() {
  local out="$1"
  shift
  : >"$out"
  jq -r '.results[] | .page' "$TMP/body.json" | while read -r page; do
    local ok=0
    for needle in "$@"; do
      if [[ "$page" == *"/${needle}/"* ]]; then
        ok=1
        break
      fi
    done
    [[ "$ok" -eq 1 ]] || continue
    slug="$(printf '%s' "$page" | last_slug)"
    [[ -n "$slug" ]] && printf '%s\n' "$slug" >>"$out"
  done
  awk '!seen[$0]++' "$out" >"${out}.u" && mv "${out}.u" "$out"
}

write_filtered "$TMP/en.txt" en en-US
write_filtered "$TMP/de.txt" de de-DE

mkdir -p data
{
  echo "# Generated by scripts/fetch-popular.sh — do not edit by hand."
  if [[ -s "$TMP/en.txt" ]]; then
    echo "en:"
    sed 's/^/  - /' "$TMP/en.txt"
  else
    echo "en: []"
  fi
  if [[ -s "$TMP/de.txt" ]]; then
    echo "de:"
    sed 's/^/  - /' "$TMP/de.txt"
  else
    echo "de: []"
  fi
} >data/popular.yaml

hugo --minify --gc
